### ISSUE TITLE
409 error in export_community_engagement when there is an empty repository

### ISSUE THREAD

**Issue by AlejandroReBa** [gomesfernanda/some-github-metrics#14]
In this line:
https://github.com/gomesfernanda/some-github-metrics/blob/195bc616bc2db40a7dc5555dc326f2041683e6b8/github_metrics.py#L141

Next error is thrown when it finds an empty repository. (Catched by main try/catch(except))
``` 
409 {"message": "Git Repository is empty.", "documentation_url": "https://docs.github.com/enterprise/2.22/rest/reference/repos#list-commits"}
``` 
Can be solved with a nested try/catch to follow up with the next repository.

Moreover,                  

```
for commits in repo.get_commits():
    countcommit += 1
```
could be changed by
```
countcommit = repo.get_commits().totalCount
```
Implemented in this PR: https://github.com/PyGithub/PyGithub/pull/820

Thanks

**Comment by gomesfernanda** [comment]
Hi Alejandro! I'm sorry for the delay. I just fixed this bug on the PR 
https://github.com/gomesfernanda/some-github-metrics/pull/16
Let me know if it works. Thanks!

**Comment by gomesfernanda** [comment]
I tried using `repo.get_commits().totalCount` but it was still throwing me an error, so I used a basic try and except to check if the repo is empty. Not the BEST solution haha but it works

**Comment by AlejandroReBa** [comment]
@gomesfernanda thanks a lot for having a look at the issue  👍🏽 

I just passed over it with some quick fixes for a self-demo before leaving the above message; I only wanted to notify you about that because your code was very handy to me.

Regards!
