### ISSUE TITLE
Valid token. Starting process.  Invalid token

### ISSUE THREAD

**Issue by KrunchMuffin** [gomesfernanda/some-github-metrics#9]
Not sure what is going on here?
I ran 
`python github_metrics.py -t 6fcdb76xxxxxxxxxxxxxxxxxxxxxxxx035b2042b -o hakimel`

and I get the following

> Valid token. Starting process.
> 
> Invalid token

**Comment by gomesfernanda** [comment]
This error message is wrongly generalized, I will fix it. :)

**Comment by gomesfernanda** [comment]
@KrunchMuffin I changed the message to be printed to be the exception error.

What happened was that your token was right, but some other error occurred. And, as the message was very specific for a non-specific error, you got the message for "invalid token" for another error. (Tell me if I didn't make myself clear)

Now you'll be able to get the right error message (if it still happens) and you're welcome to come back so we can handle it.

**Comment by gomesfernanda** [comment]
(no further comments on this, so I closed the issue)
